Docker integration
duha54rus/Discord-Music-Bot pull request #41
Opened 2021-02-10 10:28 UTC by duha54rus

Discord-music-bot can now be built into a Docker image and deployed as a container onto any server with internet connection.
## Warning! 👇🏼 
❗ The inner works of bot.py have been altered (import of a *token* and *prefixes* through **environment variables**), so the previous version of the bot, if upgraded, may end up **broken** if not reconfigured ❗

2021-02-10 11:39 UTC, piunov1998 commented
А может не стоит сливать все в одну версию? Оставить два бранча. Один для локального запуска, второй для серверного, или там остается поддержка локального старта без докера?

2021-02-10 11:52 UTC, duha54rus commented
> А может не стоит сливать все в одну версию? Оставить два бранча. Один для локального запуска, второй для серверного, или там остается поддержка локального старта без докера?

@piunov1998 Сохранится. Правда запуск надо делать через подготовленную консоль (или через скрипты, или с заполненными вручную переменными среды)

2021-02-16 14:05 UTC, duha54rus commented
@piunov1998 Прошла неделя. Может сделаешь ревью кода уже?)

2021-02-18 14:07 UTC, piunov1998 commented on cogs/music.py
> +            'outtmpl': './music/%(title)s.%(ext)s',
Use music_path variable

2021-02-18 14:08 UTC, piunov1998 requested changes

2021-02-18 14:08 UTC, piunov1998 commented on cogs/music.py
> +            'outtmpl': './music/%(title)s.%(ext)s',
Use music_path variable

2021-02-18 14:30 UTC, duha54rus commented on cogs/music.py
> +            'outtmpl': './music/%(title)s.%(ext)s',
Fixed

2021-02-18 14:36 UTC, piunov1998 approved these changes
Good one

2021-02-18 14:40 UTC, merged