Localization
duha54rus/Discord-Music-Bot pull request #56
Opened 2021-03-10 22:34 UTC by duha54rus

Adds a Russian translation to every message in the bot and its modules
Also fixes #51 (since a certain someone was really against pushing it to master...)

TODO before merging:
- [ ] Add a feature to change the language of bot messages on the fly

2021-03-10 22:41 UTC, piunov1998 commented on cogs/music.py
>                  await self.boxed_print(ctx, 'Unable to delete song file, probably it is being playing now.')
Need to translate this one

2021-03-10 22:41 UTC, piunov1998 commented on cogs/music.py
>                  await self.boxed_print(ctx, 'Unable to delete song file')
and this one

2021-03-10 22:44 UTC, piunov1998 requested changes
It would be better to 

- [x] merge new `skip` command into `localization` branch, 
- [ ] translate it 
- [ ] and after all merge this one into `master`

2021-03-23 14:23 UTC, duha54rus commented
Screw the 'on the fly' thing
On the start is the way lol

2021-03-23 14:36 UTC, piunov1998 requested changes
can u add missing translation?

2021-03-23 16:33 UTC, piunov1998 approved these changes
Add localization manual to readme file and merge

2021-03-23 16:50 UTC, merged